language: node_js
dist: xenial
os: linux
node_js:
  - "12"
services:
  - xvfb
sudo: required
addons:
  chrome: stable
  firefox : latest
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm i chromedriver@latest --no-save
script:
  - mkdir -p dist
  - npm run test:ci
  - npm run e2e:protractor
after_success:
  - npm install -g codecov
  - codecov
